site_name: InterLab
site_description: InterLab - toolkit for multi-agent interactions
site_author: Ada Böhm, Tomáš Gavenčiak
repo_url: https://github.com/acsresearch/interlab
site_url: https://acsresearch.org/interlab/

nav:
  - Home: index.md
  - Getting started: installation.md
#  - Overview: overview.md  # TODO: update overview
  - Examples: examples.md
  - Tracing:
      - Basics: tracing/basics.md
      - Serialization: tracing/serialization.md
      - Storage:  tracing/storage.md
      - Data Browser:  tracing/databrowser.md
  - Actors:
      - Basics: actors/basics.md
      - Implementing actors: actors/custom.md
      - Memory systems: actors/memory.md
      - Web console actor: actors/webactor.md
  - Environments:
      - Basics: environments/basics.md
      - Implementing environments: environments/custom.md
  - API docs: api/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - admonition

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
  - mike:
      canonical_version: stable
  - pdoc:
      api_path: api

extra:
  analytics:
    provider: google
    property: G-TM8J8R5GJ9
  version:
    provider: mike
    default: stable
  pdoc:
    api_path: api

extra_css:
  - stylesheets/extra.css
